pipeline:
  name: Rootless CI and STO
  identifier: Rootless_CI_and_STO
  projectIdentifier: SKOActon
  orgIdentifier: default
  description: Experimental situations running CI and STO in situations where customers cannot use root, --privileged, or Docker-in-Docker in secure environments.
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: Nic_Github_Cloud
        repoName: nginxinc/docker-nginx
        build: <+input>
  stages:
    - stage:
        name: Build and Security
        identifier: Build_and_Security
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
          execution:
            steps:
              - step:
                  type: Run
                  name: BuildKit
                  identifier: BuildKit
                  spec:
                    connectorRef: Nics_Dockerhub
                    image: moby/buildkit:master-rootless
                    shell: Sh
                    command: |-
                      cd stable/alpine-slim/
                      buildctl build --output type=image,name=docker.io/tuffacton/nginx,push=true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.sesandboxdelegate
              namespace: builds
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
