pipeline:
  name: Rootless CI and STO
  identifier: Rootless_CI_and_STO
  projectIdentifier: SKOActon
  orgIdentifier: default
  description: Experimental situations running CI and STO in situations where customers cannot use root, --privileged, or Docker-in-Docker in secure environments.
  tags: {}
  stages:
    - stage:
        name: Build and Security
        identifier: Build_and_Security
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          caching:
            enabled: true
            paths: []
          execution:
            steps:
              - step:
                  type: GitClone
                  name: GitClone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: Nic_Github
                    repoName: tuffacton/harness-playground
                    build:
                      type: branch
                      spec:
                        branch: main
              - step:
                  type: Run
                  name: BuildKit
                  identifier: BuildKit
                  spec:
                    connectorRef: Nics_Dockerhub
                    image: moby/buildkit:master-rootless
                    shell: Sh
                    command: |-
                      buildctl --addr tcp:10-48-5-20.nicacton.buildkitd.cluster.local \
                      build --frontend dockerfile.v0 --local context=docker_build --local dockerfile=docker_build/Dockerfile
                    resources:
                      limits:
                        memory: 500M
                        cpu: "1"
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.sesandboxdelegate
              namespace: nicacton
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
