apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
  name: harness-project
  annotations:
    # The terraform workspace will be named 'harness-project'. If you omit this
    # annotation it would be derived from metadata.name - e.g. 'example-inline'.
    crossplane.io/external-name: harness-project
spec:
  providerConfigRef:
    name: harness
  forProvider:
    # Workspaces default to using a remote source - like workspace-remote.yaml.
    # For simple cases you can use an inline source to specify the content of
    # main.tf as opaque, inline HCL.
    source: Inline
    module: |
      resource "harness_platform_project" "test" {
        identifier = "test_project"
        name       = "Test Project"
        // This can be modified but for now we'll use the default available in all new Harness accounts
        org_id     = "default"
        color      = "#0063F7"
      }