apiVersion: tf.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  # Note that unlike most provider configs this one supports an array of
  # credentials. This is because each Terraform workspace uses a single
  # Crossplane provider config, but could use multiple Terraform providers each
  # with their own credentials.
  credentials:
  - filename: gcp-credentials.json
    source: Secret
    secretRef:
      namespace: upbound-system
      name: gcp-creds
      key: credentials
  # This optional configuration block can be used to inject HCL into any
  # workspace that uses this provider config, for example to setup Terraform
  # providers.
  configuration: |
      provider "harness" {
        endpoint   = "https://app.harness.io/gateway"
        account_id = "SAsyUUHTTImuYSZ35HPDvw" 
      }
      resource "harness_platform_organization" "tf_org" {
        identifier  = "sample_terraform_org"
        name        = "Sample Terraform Org"
        description = "An example organization created by Terraform"
      }

      }


