apiVersion: tf.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: harness
spec:
  configuration: |
    terraform {
      backend "kubernetes" {
        secret_suffix = "providerconfig-default"
        namespace = "upbound-system"
        in_cluster_config = true
      }
      required_providers {
        harness = {
          source = "harness/harness"
          version = "0.32.5"
        }
      }
    }

    variable "endpoint" {
      type = string
      description= "The API endpoint for Harness, typically https://app.harness.io/gateway"
    }

    variable "account_id" {
      type = string
      description = "The unique identifier for your Harness account"
    }

    variable "platform_api_key" {
      type = string
      description = "The API (PAT or SAT) key for accessing the Harness platform https://developer.harness.io/docs/platform/automation/api/add-and-manage-api-keys/"
      sensitive = true
    }

    provider "harness" {
      endpoint = var.endpoint
      account_id = var.account_id
      platform_api_key = var.platform_api_key
    }
  credentials:
    - filename: terraform.tfvars.json
      secretRef:
        key: credentials
        name: harness-credentials
        namespace: upbound-system
      source: Secret